openapi: 3.0.0
info:
  title: Jarvis
  contact: {}
  version: '1.0.1'
servers:
- url: http://localhost:3000
  variables: {}
paths:
  /:
    get:
      tags:
      - Misc
      summary: Test
      description: This is a test request.
      operationId: Test
      parameters: []
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
tags:
- name: Misc
  description: ''
