openapi: 3.0.0
info:
  title: Jarvis
  contact: {}
  version: '1.0'
servers:
- url: http://localhost:3000
  variables: {}
paths:
  /:
    get:
      tags:
      - Misc
      summary: Test
      description: This is a test request.
      operationId: Test
      parameters: []
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /auth/signup:
    post:
      tags:
      - Misc
      summary: Test2
      description: This is another test.
      operationId: Test2
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - email
              - password
              type: object
              properties:
                email:
                  type: string
                  description: required
                  example: toto@to.to
                password:
                  type: string
                  description: required
                  example: azerty
        required: false
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
tags:
- name: Misc
  description: ''
